import { chromium } from "playwright"
const out = new URL("./screens", import.meta.url).pathname
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1200, height: 860 }, deviceScaleFactor: 2 })
const errors: string[] = []
page.on("pageerror", (e) => errors.push(e.message)); page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()) })
const shot = (name: string) => page.screenshot({ path: `${out}/${name}.png` })
await page.goto("http://localhost:5173/"); await page.waitForTimeout(400)
await page.getByRole("button", { name: "reset", exact: true }).click(); await page.waitForTimeout(200)
await shot("01-empty")
await page.locator('wg-content').click()
await page.keyboard.type("I slept kind of badly again and I think I stayed up too late scrolling. Work was fine but I kept avoiding the one thing I actually needed to finish. I felt better after walking to get coffee though. I should probably text Sam back because I've left that sitting for two days. I also keep thinking I want to do something different with my weekends instead of losing Saturday mornings.", { delay: 0 })
await page.waitForTimeout(300)
await shot("02-writing")
await page.waitForTimeout(1900)   // idle timer fires at 2000ms after the last keystroke
await page.waitForTimeout(120); await shot("03-lift")
await page.waitForTimeout(420); await shot("04-move")
await page.waitForTimeout(600); await shot("05-settle")
await page.waitForTimeout(2200); await shot("06-structured")
const want = page.locator('.block', { hasText: "want to do something different" }).first()
await want.hover(); await page.waitForTimeout(250); await shot("07-hover")
await want.locator('.more').first().click(); await page.waitForTimeout(250); await shot("08-tend-menu")
await page.mouse.click(900, 700); await page.waitForTimeout(200)
await page.getByRole("button", { name: "no" }).first().click(); await page.waitForTimeout(1300)
await page.mouse.move(900, 700); await page.waitForTimeout(300); await shot("09-after-no")
await page.keyboard.press("/"); await page.waitForTimeout(250); await shot("10-command")
await page.keyboard.type("Don't turn casual thoughts into tasks."); await page.keyboard.press("Enter"); await page.waitForTimeout(1300)
await page.mouse.move(900, 700); await page.waitForTimeout(200); await shot("11-steered")
await page.keyboard.press("/"); await page.keyboard.type("reset to defaults"); await page.keyboard.press("Enter"); await page.waitForTimeout(1300)
await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(200)
const drag = async (text: string, tx: number, ty: number) => {
  const span = page.locator('.flow [data-flip], .pinned-layer [data-flip]', { hasText: text }).first()
  const b = (await span.boundingBox())!
  await page.mouse.move(b.x + 30, b.y + 10); await page.mouse.down()
  await page.mouse.move(b.x + 200, b.y + 20, { steps: 8 })
  await page.mouse.move(tx, ty, { steps: 10 })
  await page.mouse.up(); await page.waitForTimeout(500)
  console.log("pins after", text, await page.evaluate(() => JSON.parse(localStorage.getItem("malleable-paper.events.v2")!).filter((e: any) => e.kind === "block_pinned").map((e: any) => `${e.objectId}:${e.payload.x},${e.payload.y}`)))
}
await drag("stayed up too late scrolling", 820, 150)
await drag("slept kind of badly again", 830, 225)
await page.mouse.move(600, 800); await page.waitForTimeout(300); await shot("12-pinned-near")
const c = page.getByRole("button", { name: "connect these?" }); console.log("connect", await c.count()); if (await c.count()) { await c.click(); await page.waitForTimeout(400) }
await drag("walking to get coffee", 850, 300)
await page.mouse.move(600, 800); await page.waitForTimeout(300); await shot("13-nest-offer")
const g = page.getByRole("button", { name: "group under?" }); console.log("nest", await g.count()); if (await g.count()) { await g.click(); await page.waitForTimeout(600) }
await page.mouse.move(600, 800); await page.waitForTimeout(200); await shot("14-connected-nested")
await page.keyboard.down(" "); await page.waitForTimeout(300); await shot("15-raw-hold"); await page.keyboard.up(" ")
await page.locator('.inspector-bar').click(); await page.waitForTimeout(300); await shot("16-inspector")
await page.locator('.inspector-bar').click(); await page.waitForTimeout(200)
await page.getByTitle("frame to the right").click(); await page.waitForTimeout(500); await shot("17-frame-right-empty")
await page.locator('wg-content').click(); await page.keyboard.type("I need to call the bank. Why is this so hard? The article about sleep debt was good.")
await page.waitForTimeout(4200); await shot("18-frame-right")
console.log("errors:", errors)
await browser.close()
