import { chromium } from "/Users/juliandorsey/Code/malleable-paper/prototypes/interaction/node_modules/playwright/index.js";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto("http://localhost:5174", { waitUntil: "networkidle" });
await page.waitForTimeout(2500);
await page.keyboard.press("ArrowRight");
await page.keyboard.press("ArrowRight");
await page.waitForTimeout(400);
console.log("cards:", await page.locator(".card").count());
console.log("blurb:", (await page.locator(".card-blurb").first().textContent())?.slice(0, 60));
console.log("radios:", await page.locator(".card.pending input[type=radio]").count());
await page.screenshot({ path: "web/shots/05-card-blurb.png", fullPage: false });
await browser.close();
