import { chromium } from "/Users/juliandorsey/Code/malleable-paper/prototypes/interaction/node_modules/playwright/index.js";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto("http://localhost:5174", { waitUntil: "networkidle" });
await page.waitForTimeout(2500);
await page.keyboard.press("ArrowRight");
await page.keyboard.press("ArrowRight");
await page.waitForTimeout(400);
const card = page.locator('.card:has-text("Schema conventions")');
console.log("status:", await card.locator(".card-status").textContent());
console.log("fields:", await card.locator(".card-field").count());
console.log("buttons:", await card.locator(".card-buttons button").allTextContents());
console.log("discussion lines:", await card.locator(".card-discuss").count());
// discuss round-trip on the real card? no — Julian's to rule. verify discuss on test card
const tc = page.locator('.card:has-text("test card")');
await tc.locator('textarea').fill('probe discuss');
await tc.locator('button.discuss').click();
await page.waitForTimeout(2500);
console.log("test card after discuss:", await tc.locator(".card-status").textContent(), "(want pending)");
await page.screenshot({ path: "shots/06-card-discuss.png" });
await browser.close();
